name = "booksnbrew"
compatibility_date = "2026-04-08"

pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "books-and-brews-crm"

[[r2_buckets]]
binding = "ASSETS"
bucket_name = "assets"
